[package]
name = "zeus_render"
version = "0.1.1"
authors = ["Vasilis Mourtzis <vasilis.mourtzis@outlook.com>"]
edition = "2018"

[dependencies]
zeus_core = { path = "../zeus_core", version = "0.1.0"}
image = "0.21"
gfx-hal = "0.6"
gfx-auxil = "0.7.0"
gfx-backend-vulkan = "0.6"
winit = { version = "0.24.0", features = ["web-sys"] }
env_logger = "0.7"
log = "0.4"
glsl-to-spirv = "0.1"
tobj = "2.0.3"

imgui       = { version = "0.0.23", optional = true }
imgui-winit = { package = "imgui-winit-support", version = "0.0.23",  optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.5", features = ["windef", "libloaderapi"] }

[build-dependencies]
clippy = {version = "*", optional = false }

[features]
imgui-experiment = ["imgui", "imgui-winit"]