name: Dev Build

# We will only trigger on PR check
trigger: none
pr: none

pool:
  vmImage: windows-2019

# Stages
stages: 
  - stage: check
    displayName: Check and Test Engine
    jobs:
    - template: ./stages/check.yml
  # - stage: build
  #   displayName: Build Engine
  #   jobs:
  #   - template: ./jobs/build.yml
  #     dependsOn: [test, check]
